apiVersion: v1
kind: Service
metadata:
  name: graph-node
  namespace: bohr-test
  labels:
    app.kubernetes.io/name: graph-node
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: websocket
      protocol: TCP
      name: websocket
    - port: 8020
      targetPort: index
      protocol: TCP
      name: index
    - port: 8030
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8040
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: graph-node
