apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-relayernode
  namespace: bohr-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bridge-relayernode
  template:
    metadata:
      labels:
        app: bridge-relayernode
    spec:
      containers:
        - name: bridge-relayernode
          image: 630968570112.dkr.ecr.ap-northeast-1.amazonaws.com/bohr-test/bridge-relayernode:test-73220f-20260115144352
          command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
          stdin: true
          tty: true
          env:
            - name: TRON_API_KEY
              value: "49d96339-a7e5-48b7-bf15-ee511bb8da41"
            - name: FAILED_JOB_INTERVAL
              value: "300"
            - name: MYSQL_DATABASE
              value: "bridge"
            - name: MYSQL_USERNAME
              value: "bridge_user"
            - name: MYSQL_PASSWORD
              value: "WbVyC0cxipABh9Zo1KaW"
            - name: MYSQL_HOST
              value: "chain-instance-1.cbagk0a62xfv.ap-northeast-1.rds.amazonaws.com"
            - name: MYSQL_PORT
              value: "3306"
            - name: REDIS_HOST
              value: "bohr-test.i2m8rw.clustercfg.apne1.cache.amazonaws.com"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
