[Eth]
NetworkId = 677
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 47619047620
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0xfbfF2FdC957a1bb762c8FC7B81C04D73C4F81007"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 47619047620
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://38e395894308c40477089377509ba6676dc6e2fe2dbb69e11c8f08793b13c7eea79fa884c973cd2da25f55faaf67fab0c51f2d851add2411cf24ad02a873916f@18.179.76.29:30303",
    "enode://e600aceed45952230c07838e0d7e55f975bc4f760faf01c768c2c00d155927d64d855144ca8180a8733316d16d1b51eacae9d1f9b19bf51ea0f92a94ed93492f@52.68.163.149:30303",
    "enode://aad0f9ca866ab5850ef19a91d128c1fa1c5aa9343e0553e810c4a9a90381f44005d704d3403b4246fe173c67a8639eb31ef7c2720d0a54e379f86e7432ce9828@54.64.166.104:30303",
    "enode://5673967358559592b6d99c2eb41b6d10f05a1d83524cafbd8aaa6311d84fb337543f7b8e8ab1dc97ba91b4e5f908e44302a96f0d2b8057b001ed7fb6639a366a@35.75.248.115:30303",
    "enode://a1b653a3dcfbd0ff53527d701fa90efd115764ff2387b0da746484f1e40fb4847d9b05ef59ccedb6e9df795fee3ef9ccdee5305e07e4377b8ad334257cdfb8ec@18.176.87.178:30303",
    "enode://8d92d1eb3150632e263e28bc23585bc6ebf1f7aacbfd0e966407e3ab0563b537e3d77970d9f5cc29fbf6e368410a5aea430e4a51160ac70fae38d07116f49f1b@35.73.218.11:30303",
    "enode://e575dc6663068b76134bc6ca222c37b02d2d42025c1b382f758a8752a4edf4296dd033574ea4daea2b8c1c4c58718f1bbf212e977156e2ba90610fa3eec39bbf@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
