[Eth]
NetworkId = 677
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 47619047620
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0xfbfF2FdC957a1bb762c8FC7B81C04D73C4F81007"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 47619047620
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://711644d33808b9b9734c1b8b9adb946e39960a0533f1afb68a6ff51890cf5d3c8a432e67db8846e6d5a80c99a6217f06546e4195386e9948245335e09ec066e4@18.179.76.29:30303",
    "enode://104c42134a8bf8dc954e430e1e0e62aded74b4536156a44c1119a80757b8bc9368ba1cb8a4d3d3ed985b62f6626d75045d90282708b048aa4da4f4fd32aff97a@52.68.163.149:30303",
    "enode://ce3dd55866f669d2f09016c27194cde5ae52624d7c7b6f0f8ee8ae2bdba027ac78a192ad449743371e15d12200c1d2ba16ec2ac6de2e88ccd1c6b2c3a1ab0b99@54.64.166.104:30303",
    "enode://a7322debb3c33897d3c159f030a77c41bbd50360ba0eef872d81e89afc430e74c99936f4204f72e9c9e2caf0f800130c67f65e765d03638c7520e8113bd4977f@35.75.248.115:30303",
    "enode://485e8259cebfe798137c59ef28ebe52dd8d52c26e59d88bfe3d772d7b97926571856935fe32f6dcd35eb4f0ee93533f783feb773933fead92cf204364074ca8b@18.176.87.178:30303",
    "enode://34ea46f145cc0eb94763399490535ee553661ee9840bd66ddad2841e0f8e0eb6c52d23a6ae516eb90c1e1fa4a7d01f89c92eb94bdb256cad8e151083ec6a0884@35.73.218.11:30303",
    "enode://f051f3ea3b13ec100a72ac381d096325d76cfa8529617b2040da2e896538ad439f6e3e8d299876854a47c63375be0ab44e509cb3151e04a8277aa7e77ab16c88@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
