[Eth]
NetworkId = 677
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 47619047619
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0xfbfF2FdC957a1bb762c8FC7B81C04D73C4F81007"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 47619047619
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://42ab750672f821b73d5ec5a1716105e1733713e0f312bfcfe9f210e28f4e88e38bd99d4906217893df11070b22ce4ab247022c8fbbebc547a47f2a1c72f533d4@18.179.76.29:30303",
    "enode://2c1905b8a5e5be5c021dda48334aabed3b7fdd572d6e6196546aaee6961bac73fdb7c83e961238996e06235ae1cef25aea76ab22cb022a491854ae65b38fd537@52.68.163.149:30303",
    "enode://536fbef2a4c15f055a628ee5335623df0c7f6d1617eb472ee07845525b3a10fa9ec6b594ee60b472ae4a5c065c11efc675d88271d1b3b169b8c6aec60467e4d6@54.64.166.104:30303",
    "enode://e4a570ac45ce6535a5d11d4c8745fd398536a3eee8ebe6cb898f06fd732b7a0de5c46e9a986b526771274892a10e2e4ff80ad64a1801c9db25abc0b41fd33fac@35.75.248.115:30303",
    "enode://485e8259cebfe798137c59ef28ebe52dd8d52c26e59d88bfe3d772d7b97926571856935fe32f6dcd35eb4f0ee93533f783feb773933fead92cf204364074ca8b@18.176.87.178:30303",
    "enode://28440dab229e6881e741e70c557aeb29ea13d75aca63188e5152dbd6e4c2365cccb5879db30568422b0434edec47daee2205816cc48a23a9555c4c2eb1ead6f9@35.73.218.11:30303",
    "enode://baa2844561f6278e437568628b89f7f672696ba7833788941568875874f0f18e902db1b010a6a8e2f9e49d23230c864016d64a44ab4bc0d6f9330de1384ca06f@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
