[Eth]
NetworkId = 77
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://7040c809482cc6c4e68febe5aced98555a7d6679a7f65ab2e7c616eeeb01bd54cf26bb36260b5939458198211b612bebf6026ae4dc30b29fa50d0716a766c906@18.179.76.29:30303",
    "enode://0c933c8c3488b37d9fd9ac325641e3f1921601bd009772c083869900c41ae197c1bd43c4d7a907a007672b8cd6806229eda4f173c3e5b03cd25106100cf76602@52.68.163.149:30303",
    "enode://e6b186e9e591bbe77a111a313fc971d487d7908a2ab30b03d71a4cf60af7522534dd930c219a1cc6d2b894ee64e6f9667cb06db4187890d306adc448d8ccf4d9@54.64.166.104:30303",
    "enode://fdc841321d8b5ac0aed47cec0aad20025331cb81d6dae553c2eb703e511d45a48228468af219e1b38044d3d805acbe193c539bcd7c35f50b16526a9fc6cf2344@35.75.248.115:30303",
    "enode://9849648ba278f2b86cba7fe93b05a9dfe7b7ab38d34232a32548fdd0fa11f941cfa294a6f1c9abbc0921d2bc2c8bc3dae76f379b85071310ef8680a178452b17@18.176.87.178:30303",
    "enode://e1b4ca70afeb231c7f0dddedef5a18be17df3fbb2eefca4ba8bde2bb0e3593813d42a7dbe71edfea91b7918942d6f9560cb357b299d0301e9c4860e165ab05de@35.73.218.11:30303",
    "enode://8a36695646c0665a1e979088a4343c776d6efa3f6c956f52dac583666918e1560095b5c55b76d6858e4dc180219b966a9f6022b89676ed03f7194c893e665f93@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
