[Eth]
NetworkId = 677
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 47619047619
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0xfbfF2FdC957a1bb762c8FC7B81C04D73C4F81007"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 47619047619
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://8f33f97bdabef1058bd340ebc8ec8849f02e9cd608a07fded227e1cc8836c6d4c759bc22c566fb4bc7cdca6187a366be48543827e58435268d512751765fe60a@18.179.76.29:30303",
    "enode://612f7538833a6dc22227b4807f5a082dba1f902f9efc217f038bee2822889738a083c26a4992b570621b351dee8d263c00c22c3ab42440e165a4f9eae44995cc@52.68.163.149:30303",
    "enode://fc738f90b0c2b4a8dc768e9908a8e8dfbe400db1eb588c26d4240d7d7dd73291168e947c86fb33862f23708abbca5e5b38127c4a75ab59e4066e9f91cc240dfd@54.64.166.104:30303",
    "enode://8b8ccfb21ef802f7ea9ad4fdf2667b01c4ec1de00086607fa9c03fdb865c8f8fc0df20e6cd3b0fd3c018ea4fe6b37c8f55feaab9ef445bb2d3beda2390881047@35.75.248.115:30303",
    "enode://e510e0ae0d5d66560fdbf82dc7ecd62a4d688c17d4be4958a22aa1dc9737f26aabc6f4696a1f8f2ecb52a537b74ff0953b3444533db3f738056b00188ee7294a@18.176.87.178:30303",
    "enode://c9ba9c8ccd6df44b2c43f380e5173742a070e96d443bbe544e9e5374ed25501b6bc75d668c2db9f48fa10046e2743239c461537b052271962b8a0c53dc1b8837@35.73.218.11:30303",
    "enode://3eddcbf9669e2f532610a3a74e0f9c8c64ca2ee6b64360dd376828a44e237bf74b5ea611cfb467b6d9e59bb2545163c1ae725378350ee991ecfe42cb76230bee@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
