[Eth]
NetworkId = 77
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://7040c809482cc6c4e68febe5aced98555a7d6679a7f65ab2e7c616eeeb01bd54cf26bb36260b5939458198211b612bebf6026ae4dc30b29fa50d0716a766c906@18.179.76.29:30303",
    "enode://ad9637c8d282b78af4e24d11fe0a8709f0569ea0c024eac58c7ebd6e40bb2d2899ef03c5d02fd11a797eab245476332f081cf28913dc361156c3d451dc16d723@52.68.163.149:30303",
    "enode://2aa57fd2f10631fa06a29537542d69d457bd0851e1f4432b0068d23c5ff1a9354a4ff0b1cd8ca98c3bad607d23160b33f8914fef18cb20a9aa79853a6c5dca38@54.64.166.104:30303",
    "enode://571f924ab0aeca7783bcc95a9059fdf5ca706ab056a86f262bc31b15b5ec225c0d2e1b00792ab72c47d6d8de811ffa2e34cb943b2f22c5a82f10b1d3d34fa86b@35.75.248.115:30303",
    "enode://bab5c3f1011f5e3cf80aa42cb5da8687a0e743cc447478650a984485b4084fc5889fea9939ccac03598f11dba89f8255c7cf83ad71b044c8356d5f3db5fb30f9@18.176.87.178:30303",
    "enode://70bd5c0995be918e6fd70c5a16a011aa1ca6134ba39955494bf916f47c634cd0e2e143e779940ea576dc4e27e75edf8012e798d24eec1f9f392595b8bfd89f64@35.73.218.11:30303",
    "enode://a57be98d126a04a93358656aba966426c11f92b88ce0f2a6e201ee60e89c3e5f2eaf3d3d9bc65c24fc2e0808fd95fc2dd1e91d8365266b0f18133e4b5e6971fa@18.180.116.96:30303",
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
