apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rpc-ws-ingress
  namespace: bohr-prod
  annotations:
    # WebSocket 专用长连接配置（关键！）
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400" # 24小时长连接
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
#    nginx.ingress.kubernetes.io/limit-rps: "50"
#    nginx.ingress.kubernetes.io/limit-burst: "100"
    # 启用并配置CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx-public
  rules:
    - host: ws-rpc.botchain.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chain-node-rpc
                port:
                  number: 8546  # 明确指向WebSocket端口
