apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - name: ipfs
          image: ipfs/kubo:v0.26.0
          ports:
            - containerPort: 4001  # swarm
            - containerPort: 5001  # api
            - containerPort: 8080  # gateway
          volumeMounts:
            - name: ipfs-data
              mountPath: /data/ipfs
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
            claimName: ipfs-data
